# Generated by Django 5.0.3 on 2024-03-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_password', models.TextField()),
                ('customer_contact', models.TextField()),
                ('customer_address', models.TextField()),
                ('customer_profile_image', models.FileField(upload_to='customer_profile_images')),
            ],
        ),
    ]
