# Generated by Django 5.0.3 on 2024-03-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerregistration',
            name='customer_contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customerregistration',
            name='customer_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customerregistration',
            name='customer_profile_image',
            field=models.ImageField(upload_to='customer_profile_images'),
        ),
    ]
